### ISSUE TITLE
Which flutter version does this app use?

### ISSUE THREAD

**Issue by soumyaDghosh** [Merrit/feeling_finder#67]
Hii, while creating the snap package for this app, every time, I am facing this error.

```
:: [   +3 ms] pub get failed (1; ---- End log transcript ----)
:: [        ]
::            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
::            #1      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:373:7)
::            <asynchronous suspension>
::            #2      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:254:7)
::            <asynchronous suspension>
::            #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1301:7)
::            <asynchronous suspension>
::            #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
::            <asynchronous suspension>
::            #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
::            <asynchronous suspension>
::            #6      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
::            <asynchronous suspension>
::            #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
::            <asynchronous suspension>
::            #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
::            <asynchronous suspension>
::            #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
::            <asynchronous suspension>
::            #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
::            <asynchronous suspension>
::            #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
::            <asynchronous suspension>
::            #12     main (package:flutter_tools/executable.dart:94:3)
::            <asynchronous suspension>
::
```

I guess it has something with the mismatch of flutter version. I have tried versions `3.10.0` and `2.10.0`. The above error log is for version `2.10.0`. Your help in this regard is requested. Thanks.

**Comment by Merrit** [comment]
Hi, Flutter should be around the stable version, which is currently 3.10.3, though it should probably work with anything over v3.

I haven't seen this particular error before, but a couple things to try:

- Run `pub get` with the verbose flag, see if there is more info on the error
- Check with how [this repo](https://github.com/CapeCrusader321/feeling_finder-snap) builds the snap

**Comment by soumyaDghosh** [comment]
>     * Check with how [this repo](https://github.com/CapeCrusader321/feeling_finder-snap) builds the snap

I am trying to help him with that snap, cause using a already built file isn't always a viable option. But, I will try to keep your suggestions in mind. 

Do you have any github action which normally builds this using flutter?

**Comment by Merrit** [comment]
> Do you have any github action which normally builds this using flutter?

https://github.com/Merrit/feeling_finder/blob/main/.github/workflows/build-linux.yml

Had a thought: in the build environment, make sure it has access to the internet because `pub get` pulls packages from the pub repo.

**Comment by soumyaDghosh** [comment]
```
:: FINE: Resolving dependencies finished (0.208s).
:: [ +431 ms] pub failed
::            command: "/build/snapcraft-feeling-finder-f01e7fd244c9a30ab3a844ec168c21f3/parts/flutter-git/install/usr/libexec/flutter/bin/cache/dart-sdk/bin/dart pub --suppress-analytics run flutter_app_builder -v --platforms=linux"
::            pub env: {
::              "FLUTTER_ROOT": "/build/snapcraft-feeling-finder-f01e7fd244c9a30ab3a844ec168c21f3/parts/flutter-git/install/usr/libexec/flutter",
::              "PUB_ENVIRONMENT": "flutter_bot:flutter_cli:forward",
::            }
::            exit code: 66
::
:: [   +9 ms] "flutter run" took 516ms.
:: [   +2 ms]
::            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
::            #1      _DefaultPub._runWithStdioInherited (package:flutter_tools/src/dart/pub.dart:447:7)
::            <asynchronous suspension>
::            #2      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:530:5)
::            <asynchronous suspension>
::            #3      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:122:5)
::            <asynchronous suspension>
::            #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
::            <asynchronous suspension>
::            #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
::            <asynchronous suspension>
::            #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
::            <asynchronous suspension>
::            #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
::            <asynchronous suspension>
::            #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
::            <asynchronous suspension>
::            #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
::            <asynchronous suspension>
::            #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
::            <asynchronous suspension>
::            #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
::            <asynchronous suspension>
::            #12     main (package:flutter_tools/executable.dart:91:3)
::            <asynchronous suspension>
::
::
:: [  +11 ms] ensureAnalyticsSent: 0ms
:: [        ] Running 0 shutdown hooks
:: [        ] Shutdown hooks complete
:: [        ] exiting with code 66
```

This is from flutter version `3.10.0` and yes, it has internet access

**Comment by Merrit** [comment]
> `dart pub --suppress-analytics run flutter_app_builder -v --platforms=linux`

Try the regular build command: `flutter build linux`
